opensearch-project/opensearch-testcontainers

- MAINTAINERS.md
- PULL_REQUEST_TEMPLATE.md
- README.md
- RELEASING.md
- SECURITY.md
Signed-off-by: CEHENKLE <henkle@amazon.com>
Adding Maintainers to new repo
I've never cut the first issue in a repo before -- checking off an item on my bucket list ;) 
> Initial Check-in

- jenkins/publish-snapshot.jenkinsfile
Opensearch testcontainers snapshot cron
https://github.com/opensearch-project/opensearch-build/issues/2656
> Opensearch testcontainers snapshot cron

- build.gradle.kts
- jenkins/publish-snapshot.jenkinsfile
- jenkins/stage-maven-release.jenkinsfile
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Tweak and add publish official maven
https://github.com/opensearch-project/opensearch-build/issues/2656
> Tweak and add publish official maven

- build.gradle.kts
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
[Describe what this change achieves]
[List any issues this PR will resolve]
> Bumping version to 2.0.1

- README.md
- build.gradle.kts
- version.properties
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
Add version.properties and refactor version management at build time
N/A
> Add version.properties and refactor version management at build time

- jenkins/publish-snapshot.jenkinsfile
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
Add 1.x branch support for snapshot publishing
N/A
> Add 1.x branch support for snapshot publishing

- .github/workflows/main_and_pr_workflow.yml
- README.md
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
Update README.md and add JDK-17 to build matrix
N/A
> Update README.md and add JDK-17 to build matrix

- README.md
- version.properties
Updating README.md and bumping to the next version
N/A
> Updating README.md and bumping to the next version

- .github/CODEOWNERS
- MAINTAINERS.md
Added @peterzhuamazon to co-maintainers.
> Added @peterzhuamazon to co-maintainers.

- README.md
- src/test/java/org/opensearch/testcontainers/OpensearchContainerTest.java
- version.properties
Bump version to 2.0.2 and update README.md
N/A
> Bump version to 2.0.2 and update README.md

- build.gradle.kts
Update logback to 1.2.13
Closes https://github.com/opensearch-project/opensearch-testcontainers/issues/127
> Update logback to 1.2.13

- gradle/wrapper/gradle-wrapper.properties
> Update to Gradle 8.7

- build.gradle.kts
Update Testcontainers to 1.19.8
Closes https://github.com/opensearch-project/opensearch-testcontainers/issues/148
> Update Testcontainers to 1.19.8

- README.md
- version.properties
Post 2.0.2 release updates
N/A
> Post 2.0.2 release updates

- build.gradle.kts
Update Testcontainers to 1.20.0
N/A
> Update Testcontainers to 1.20.0

- README.md
- version.properties
Post 2.1.0 release updates
N/A
> Post 2.1.0 release updates

- gradle/wrapper/gradle-wrapper.properties
> Update Gradle to 8.10.1

- build.gradle.kts
Update Testcontainers to 1.20.2
N/A
> Update Testcontainers to 1.20.2

- README.md
- version.properties
Bump next version to 2.1.2
N/A
> Bump next version to 2.1.2

- README.md
- version.properties
Bump next version to 2.1.3
Post 2.1.2 release
> Bump next version to 2.1.3

- README.md
- version.properties
Bump next version to 2.1.4
N/A
> Bump next version to 2.1.4

- .github/CODEOWNERS
- MAINTAINERS.md
Add Andrew Ross (@andrross) as a mainatainer
N/A
> Add Andrew Ross (@andrross) as a mainatainer

- .github/workflows/main_and_pr_workflow.yml
- .github/workflows/publish-maven-snapshots.yml
- build.gradle.kts
- src/test/java/org/opensearch/testcontainers/OpenSearchContainerTest.java
Update to OpenSearch 3.0.0-alpha1
N/A
> Update to OpenSearch 3.0.0-alpha1

- build.gradle.kts
- src/main/java/org/opensearch/testcontainers/OpenSearchContainer.java
- src/test/java/org/opensearch/testcontainers/OpenSearchContainerTest.java
Update OpenSearch to 3.0.0-beta1
N/A
> Update OpenSearch to 3.0.0-beta1

- build.gradle.kts
Update OpenSearch to 3.0.0
N/A
> Update OpenSearch to 3.0.0

- .github/workflows/release-drafter.yml
Fix release-drafter.yml GA workflow
N/A
> Fix release-drafter.yml GA workflow

- README.md
- version.properties
Bump next version to 3.0.1
N/A
> Bump next version to 3.0.1

- src/main/java/org/opensearch/testcontainers/OpensearchContainer.java
- src/test/java/org/opensearch/testcontainers/OpenSearchContainerClusterTest.java
- src/test/java/org/opensearch/testcontainers/OpensearchContainerTest.java
Add OpenSearch cluster test case
N/A
> Add OpenSearch cluster test case

- README.md
- version.properties
Bump next version to 2.1.5
N/A
> Bump next version to 2.1.5

- README.md
- version.properties
Bump next version to 3.0.3
N/A
> Bump next version to 3.0.3

- src/test/java/org/opensearch/testcontainers/OpenSearchContainerTest.java
Add HTTP/2 specific tests
Finalizes https://github.com/opensearch-project/opensearch-testcontainers/issues/138
> Add HTTP/2 specific tests

- .github/workflows/codeql-analysis.yml
- build.gradle.kts
> Update CodeQL actions
